### ISSUE TITLE
error at the end of running the script openshift-deploy.sh

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali-test-mesh#18]
I ran this:

```
./openshift-deploy.sh test-configs/test-circle.yaml 
```

And got this error at the very end. Things look OK, but look at the error at the end - not sure if this can be ignored or not:

```
...
+ deploy_traffic_generator test-mesh
+ namespace=test-mesh
+ template=./../traffic-generator/openshift/traffic-generator.yaml
+ oc create -f ./../traffic-generator/openshift/traffic-generator.yaml -n test-mesh
replicaset "kiali-traffic-generator" created
+ deploy_traffic_configmap test-mesh
+ namespace=test-mesh
+ configmapfile=
+ oc create -f -n test-mesh
error: Unexpected args: [test-mesh]
See 'oc create -h' for help and examples.
```

**Comment by jmazzitelli** [comment]
I think this might be causing other problems. I ran this:

```
MAX_NUMBER_OF_VERSIONS=2 ./openshift-deploy.sh test-configs/test-circle.yaml
```

Got a similar error:

```
+ deploy_traffic_configmap test-circle
+ namespace=test-circle
+ configmapfile=
+ oc create -f -n test-circle
error: Unexpected args: [test-circle]
```

And now the test generator is broken - getting this error in the OS console:

```
Error: configmaps "traffic-generator-config" not found
```

**Comment by gbaufake** [comment]
@cfcosta thoughts about this issue?

**Comment by cfcosta** [comment]
I think we should remove openshift-deploy.sh, given that now we're using the ansible playbooks, or are you still using it?

**Comment by jmazzitelli** [comment]
I just found this script yesterday and found it useful. 

The README in this project is empty - no instructions on how to use this. I do not see any ansible playbooks in here - can you update the README on how to do this?
